host: '127.0.0.1'
port: 8849
user: 'nacos'
password: 'nacos'
namespace: '6af9810f-2e08-4e9e-ab52-ae2868fe5fcc'
dataid: 'user-srv.json'
group: 'dev'

#---
#name: user-srv
#mysql:
#    host: 127.0.0.1
#    port: 3306
#    user: root
#    password: root
#    db: shop_user_srv
#consul:
#    host: 127.0.0.1
#    port: 8500
